---

- name: "SCORED | 1.6.1 | PATCH | Ensure core dumps are restricted"
  block:
  - name: "SCORED | 1.6.1 | PATCH | Ensure core dumps are restricted | Update limits.conf file"
    lineinfile:
      state: present
      dest: /etc/security/limits.conf
      regexp: '^#?\\*.*core'
      line: '*                hard    core            0'
      insertbefore: '^# End of file'

  - name: "SCORED | 1.6.1 | PATCH | Ensure core dumps are restricted | Set active kernel parameter"
    sysctl:
      name: fs.suid_dumpable
      value: '0'
      state: present
      reload: yes
      sysctl_set: yes
      ignoreerrors: yes

  - name: SCORED | 1.6.1 | PATCH | Ensure core dumps are restricted | coredump.conf"
    lineinfile:
      dest: /etc/systemd/coredump.conf
      regexp: "{{ item.regex }}"
      line: "{{ item.line }}"
      create: yes
      mode: 0644
    loop:
    - { regex: '^Storage', line: 'Storage=none' }
    - { regex: '^ProcessSizeMax', line: 'ProcessSizeMax=0' }
  when:
  - rhel7cis_rule_1_6_1
  tags:
  - level1
  - scored
  - sysctl
  - patch
  - rule_1.6.1

- name: "NOTSCORED | 1.6.2 | PATCH | Ensure XD/NX support is enabled"
  shell: dmesg|grep -E "NX|XD" | grep " active"
  changed_when: no
  when:
  - rhel7cis_rule_1_6_2
  tags:
  - level1
  - patch
  - notscored
  - rule_1.5.2


- name: "SCORED | 1.6.3 | PATCH | Ensure address space layout randomization (ASLR) is enabled"
  sysctl:
    name: kernel.randomize_va_space
    value: '2'
    state: present
    reload: yes
    sysctl_set: yes
    ignoreerrors: yes
  when:
  - rhel7cis_rule_1_6_3
  tags:
  - level1
  - scored
  - patch
  - rule_1.6.3

- name: "SCORED | 1.6.4 | PATCH | Ensure prelink is disabled"
  yum:
    name: prelink
    state: absent
  when:
  - rhel7cis_rule_1_6_4
  tags:
  - level1
  - scored
  - patch
  - rule_1.6.4
