- name: "SCORED | 5.1.1 | AUDIT | Install the rsyslog package"
  command: rpm -q rsyslog
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_5.1.1

- name: "SCORED | 5.1.1 | PATCH | Install the rsyslog package"
  yum:
      name: rsyslog
      state: installed
  tags:
      - level1
      - level2
      - patch
      - rule_5.1.1

- name: "SCORED | 5.1.2 | AUDIT | Activate the rsyslog Service"
  command: systemctl is-enabled rsyslog
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_5.1.2

- name: "SCORED | 5.1.2 | PATCH | Activate the rsyslog Service"
  command: systemctl enable rsyslog
  tags:
      - level1
      - level2
      - patch
      - rule_5.1.2

- name: "NOTSCORED | 5.1.3 | AUDIT | Configure /etc/rsyslog.conf"
  shell: rpm -Vv rsyslog|grep /etc/rsyslog.conf| grep '^\.\.\.\.\.'
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_5.1.3

- name: "SCORED | 5.1.4 | PATCH | Create and Set Permissions on rsyslog Log Files"
  file:
      path: /etc/rsyslog.conf
      mode: 0640
      owner: root
      group: root
  tags:
      - level1
      - level2
      - patch
      - rule_5.1.4

- name: "SCORED | 5.1.5 | AUDIT | Configure rsyslog to Send Logs to a Remote Log Host"
  command: grep "^*.*[^I][^I]*@" /etc/rsyslog.conf
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_5.1.5

- name: "NOTSCORED | 5.1.6 | AUDIT | Accept Remote rsyslog Messages Only on Designated Log Hosts"
  command: grep '^$ModLoad imtcp' /etc/rsyslog.conf
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_5.1.6
- name: "NOTSCORED | 5.1.6 | PATCH | Accept Remote rsyslog Messages Only on Designated Log Hosts"
  lineinfile:
      dest=/etc/rsyslog.conf
      regexp='^$ModLoad imtcp'
      line='# $ModLoad imtcp.so'
      state=present
  tags:
      - level1
      - level2
      - patch
      - rule_5.1.6

- name: "NOTSCORED | 5.1.6 | AUDIT | Accept Remote rsyslog Messages Only on Designated Log Hosts"
  command: grep '^$InputTCPServerRun' /etc/rsyslog.conf
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_5.1.6

- name: "NOTSCORED | 5.1.6 | PATCH | Accept Remote rsyslog Messages Only on Designated Log Hosts"
  lineinfile:
      dest=/etc/rsyslog.conf
      regexp='^$InputTCPServerRun'
      line='# $InputTCPServerRun 514'
      state=present
  tags:
      - level1
      - level2
      - patch
      - rule_5.1.6
