- name: "SCORED | 7.3 | AUDIT | Set Default Group for root Account"
  shell: grep "^root:" /etc/passwd | cut -f4 -d:|grep 0
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_7.3

- name: "SCORED | 7.3 | PATCH | Set Default Group for root Account"
  command: usermod -g 0 root
  tags:
      - level1
      - level2
      - patch
      - rule_7.3

- name: "SCORED | 7.4 | AUDIT | Set Default umask for Users"
  command: grep "^umask 077" /etc/bashrc
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_7.4

- name: "SCORED | 7.4 | AUDIT | Set Default umask for Users"
  command: grep "^umask 077" /etc/profile.d/*
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_7.4

- name: "SCORED | 7.4 | PATCH | Set Default umask for Users"
  lineinfile:
      state: present
      create: yes
      line: 'umask 077'
      dest: /etc/bashrc
      owner: root
      group: root
      mode: "0644"
  tags:
      - level1
      - level2
      - patch
      - rule_7.4

- name: "SCORED | 7.4 | PATCH | Set Default umask for Users"
  lineinfile:
      state: present
      create: yes
      line: 'umask 077'
      dest: /etc/profile.d/cis.sh
      owner: root
      group: root
      mode: "0644"
  tags:
      - level1
      - level2
      - patch
      - rule_7.4

