- name: "SCORED | 2.1.1 | AUDIT | Remove telnet-server"
  command: rpm -q telnet-server
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.1

- name: "SCORED | 2.1.1 | PATCH | Remove telnet-server"
  yum:
    name: telnet-server
    state: absent
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.1

- name: "SCORED | 2.1.2 | AUDIT | Remove telnet Clients"
  command: rpm -q telnet
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.2

- name: "SCORED | 2.1.2 | PATCH | Remove telnet Clients"
  yum:
    name: telnet
    state: absent
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.2

- name: "SCORED | 2.1.3 | AUDIT | Remove rsh-server"
  command: rpm -q rsh-server
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.3

- name: "SCORED | 2.1.3 | PATCH | Remove rsh-server"
  yum:
    name: rsh-server
    state: absent
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.3

- name: "SCORED | 2.1.4 | AUDIT | Remove rsh"
  command: rpm -q rsh
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.4

- name: "SCORED | 2.1.4 | PATCH | Remove rsh"
  yum:
    name: rsh
    state: absent
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.4

- name: "SCORED | 2.1.5 | AUDIT | Remove NIS Client"
  command: rpm -q yp-tools
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.5

- name: "SCORED | 2.1.5 | PATCH | Remove NIS Client"
  yum:
    name: yp-tools
    state: absent
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.5

- name: "SCORED | 2.1.6 | AUDIT | Remove NIS Server"
  command: rpm -q ypserv
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.6

- name: "SCORED | 2.1.6 | PATCH | Remove NIS Server"
  yum:
    name: ypserv
    state: absent
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.6

- name: "SCORED | 2.1.7 | AUDIT | Remove tftp"
  command: rpm -q tftp
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.7

- name: "SCORED | 2.1.7 | PATCH | Remove tftp"
  yum:
      name: tftp
      state: absent
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.7

- name: "SCORED | 2.1.8 | AUDIT | Remove tftp-server"
  command: rpm -q tftp-server
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.8

- name: "SCORED | 2.1.8 | PATCH | Remove tftp-server"
  yum:
      name: tftp-server
      state: absent
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.8

- name: "SCORED | 2.1.9 | AUDIT | Remove talk"
  command: rpm -q talk
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.9

- name: "SCORED | 2.1.9 | PATCH | Remove talk"
  yum:
    name: talk
    state: absent
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.9

- name: "SCORED | 2.1.10 | AUDIT | Remove talk-server"
  command: rpm -q talk-server
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.10

- name: "SCORED | 2.1.10 | PATCH | Remove talk-server"
  yum:
    name: talk-server
    state: absent
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.10

- name: "SCORED | 2.1.11 | AUDIT | Remove xinetd"
  command: rpm -q xinetd
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level2
      - audit
      - rule_2.1.11

- name: "SCORED | 2.1.11 | PATCH | Remove xinetd"
  yum:
    name: xinetd
    state: absent
  tags:
      - level2
      - patch
      - rule_2.1.11

- name: "SCORED | 2.1.12 | AUDIT | Disable chargen-dgram"
  shell: chkconfig --list chargen-dgram | grep 'off'
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.12

- name: "SCORED | 2.1.12 | PATCH | Disable chargen-dgram"
  yum:
    name: xinetd
    state: absent
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.12

- name: "SCORED | 2.1.13 | AUDIT | Disable chargen-stream"
  shell: chkconfig --list chargen-stream | grep 'off'
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.13

- name: "SCORED | 2.1.13 | PATCH | Disable chargen-stream"
  yum:
    name: xinetd
    state: absent
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.13

- name: "SCORED | 2.1.14 | AUDIT | Disable daytime-dgram"
  shell: chkconfig --list daytime-dgram | grep 'off'
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.14

- name: "SCORED | 2.1.14 | PATCH | Disable daytime-dgram"
  yum:
    name: xinetd
    state: absent
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.14

- name: "SCORED | 2.1.15 | AUDIT | Disable daytime-stream"
  shell: chkconfig --list daytime-stream | grep 'off'
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.15

- name: "SCORED | 2.1.15 | PATCH | Disable daytime-stream"
  yum:
    name: xinetd
    state: absent
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.15

- name: "SCORED | 2.1.16 | AUDIT | Disable echo-dgram"
  shell: chkconfig --list echo-dgram | grep 'off'
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.16

- name: "SCORED | 2.1.16 | PATCH | Disable echo-dgram"
  yum:
    name: xinetd
    state: absent
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.16

- name: "SCORED | 2.1.17 | AUDIT | Disable echo-stream"
  shell: chkconfig --list echo-stream | grep 'off'
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.17

- name: "SCORED | 2.1.17 | PATCH | Disable echo-stream"
  yum:
    name: xinetd
    state: absent
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.17

- name: "SCORED | 2.1.18 | AUDIT | Disable tcpmux-server"
  shell: chkconfig --list tcpmux-server | grep 'off'
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.18

- name: "SCORED | 2.1.18 | PATCH | Disable tcpmux-server"
  yum:
    name: xinetd
    state: absent
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.18
