- name: "NOTSCORED | 6.1.1 | AUDIT | Audit system file permissions"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level2
      - audit
      - rule_6.1.1


- name: "SCORED | 6.1.2 | AUDIT | Ensure permissions on /etc/passwd are configured"
  shell: stat -L -c "%a %u %g" /etc/passwd | egrep "644 0 0"
  register: check_perm_passwd_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.1.2


- name: "SCORED | 6.1.3 | AUDIT | Ensure permissions on /etc/shadow are configured"
  shell: stat -L -c "%a %u %g" /etc/shadow | egrep "0 0 0"
  register: check_perm_shadow_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.1.3


- name: "SCORED | 6.1.4 | AUDIT | Ensure permissions on /etc/group are configured"
  shell: stat -L -c "%a %u %g" /etc/group | egrep "644 0 0"
  register: check_perm_group_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.1.4


- name: "SCORED | 6.1.5 | AUDIT | Ensure permissions on /etc/gshadow are configured"
  shell: stat -L -c "%a %u %g" /etc/gshadow | egrep "0 0 0"
  register: check_perm_gshadow_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.1.5


- name: "SCORED | 6.1.6 | AUDIT | Ensure permissions on /etc/passwd- are configured"
  shell: stat -L -c "%a %u %g" /etc/passwd- | egrep "644 0 0"
  register: check_perm_passwd2_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.1.6


- name: "SCORED | 6.1.7 | AUDIT | Ensure permissions on /etc/shadow- are configured"
  shell: stat -L -c "%a %u %g" /etc/shadow- | egrep "000 0 0"
  register: check_perm_shadow2_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.1.7


- name: "SCORED | 6.1.8 | AUDIT | Ensure permissions on /etc/group- are configured"
  shell: stat -L -c "%a %u %g" /etc/group- | egrep "600 0 0"
  register: check_perm_group2_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.1.8


- name: "SCORED | 6.1.9 | AUDIT | Ensure permissions on /etc/gshadow- are configured"
  shell: stat -L -c "%a %u %g" /etc/gshadow- | egrep "600 0 0"
  register: check_perm_gshadow2_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.1.9


- name: "SCORED | 6.1.10 | AUDIT | Ensure no world writable files exist"
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -0777 | wc -l |grep 0
  register: check_world_writable_audit
  always_run: yes
  changed_when: no
  failed_when: result.stdout != ""
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.1.10


- name: "SCORED | 6.1.11 | AUDIT | Ensure no unowned files or directories exist"
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -nouser | wc -l |grep 0
  register: check_unowned_files_audit
  always_run: yes
  changed_when: no
  failed_when: result.stdout != ""
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.1.11


- name: "SCORED | 6.1.12 | AUDIT | Ensure no ungrouped files or directories exist"
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -nogroup | wc -l |grep 0
  register: check_ungrouped_files_audit
  always_run: yes
  changed_when: no
  failed_when: result.stdout != ""
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.1.12


- name: "NOTSCORED | 6.1.13 | AUDIT | Audit SUID executables"
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -4000
  register: check_suid_executables_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  failed_when: result.stdout != ""
  tags:
      - level1
      - level2
      - audit
      - rule_6.1.13


- name: "NOTSCORED | 6.1.14 | AUDIT | Audit SGID executables"
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -4000
  register: check_SGID_executables_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  failed_when: result.stdout != ""
  tags:
      - level1
      - level2
      - audit
      - rule_6.1.14


- name: "SCORED | 6.2.1 | AUDIT | Ensure password fields are not empty"
  shell: "cat /etc/shadow | awk -F: '($2 == \"\" ) {j++;print $1; } END {exit j}'"
  register: empty_password_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.2.1


- name: "SCORED | 6.2.2 | AUDIT | Ensure no legacy '+' entries exist in /etc/passwd"
  shell: grep -c '^+' /etc/passwd | grep 0
  register: nismap_legacy_passwd_entries_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.2.2


- name: "SCORED | 6.2.3 | AUDIT | Ensure no legacy '+' entries exist in /etc/shadow"
  shell: grep -c '^+' /etc/shadow | grep 0
  register: nismap_legacy_shadow_entries_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.2.3


- name: "SCORED | 6.2.4 | AUDIT | Ensure no legacy '+' entries exist in /etc/group"
  shell: grep -c '^+' /etc/group | grep 0
  register: nismap_legacy_group_entries_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.2.4


- name: "SCORED | 6.2.5 | AUDIT | Ensure root is the only UID 0 account"
  shell: "cat /etc/passwd | awk -F: '($3 == 0 && $1 != \"root\") {i++;print $1 } END {exit i}'"
  register: uid_zero_accounts_except_root_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.2.5


- name: "SCORED | 6.2.6 | AUDIT | Ensure root PATH Integrity"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.2.6


- name: "SCORED | 6.2.7 | AUDIT | Ensure all users' home directories exist"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.2.7


- name: "SCORED | 6.2.8 | AUDIT | Ensure users' home directories permissions are 750 or more restrictive"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.2.8


- name: "SCORED | 6.2.9 | AUDIT | Ensure users own their home directories"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.2.9


- name: "SCORED | 6.2.10 | AUDIT | Ensure users' dot files are not group or world writable"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.2.10


- name: "SCORED | 6.2.11 | AUDIT | Ensure no users have .forward files"
  shell: find /root /home -xdev -name .forward|wc -l |grep 0
  register: forward_files_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.2.11


- name: "SCORED | 6.2.12 | AUDIT | Ensure no users have .netrc files"
  shell: find /root /home -xdev -name .netrc|wc -l |grep 0
  register: netrc_files_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.2.12


- name: "SCORED | 6.2.13 | AUDIT | Ensure users' .netrc Files are not group or world accessible"
  shell: find /root /home -xdev -name .netrc|wc -l |grep 0
  register: netrc_permissions_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.2.13


- name: "SCORED | 6.2.14 | AUDIT | Ensure no users have .rhosts files"
  shell: find /root /home -xdev -name .rhosts|wc -l |grep 0
  register: rhosts_files_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.2.14


- name: "SCORED | 6.2.15 | AUDIT | Ensure all groups in /etc/passwd exist in /etc/group"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.2.15


- name: "SCORED | 6.2.16 | AUDIT | Ensure no duplicate UIDs exist"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.2.16


- name: "SCORED | 6.2.17 | AUDIT | Ensure no duplicate GIDs exist"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.2.17


- name: "SCORED | 6.2.18 | AUDIT | Ensure no duplicate user names exist"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.2.18


- name: "SCORED | 6.2.19 | AUDIT | Ensure no duplicate group names exist"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_6.2.19

