- name: "SCORED | 3.1.1 | AUDIT | Ensure IP forwarding is disabled"
  shell: /sbin/sysctl net.ipv4.ip_forward|grep 0
  register: check_ipv4_forward_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_3.1.1


- name: "SCORED | 3.1.2 | AUDIT | Ensure packet redirect sending is disabled"
  shell: /sbin/sysctl net.ipv4.conf.all.send_redirects|grep 0 && /sbin/sysctl net.ipv4.conf.default.send_redirects|grep 0
  register: check_ipv4_redirects_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_3.1.2



- name: "SCORED | 3.2.1 | AUDIT | Ensure source routed packets are not accepted"
  shell: /sbin/sysctl net.ipv4.conf.all.accept_source_route|grep 0 && /sbin/sysctl net.ipv4.conf.default.accept_source_route|grep 0
  register: check_ipv4_route_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_3.2.1


- name: "SCORED | 3.2.2 | AUDIT | Ensure ICMP redirects are not accepted"
  shell: /sbin/sysctl net.ipv4.conf.all.accept_redirects|grep 0 && /sbin/sysctl net.ipv4.conf.default.accept_redirects|grep 0
  register: check_ipv4_redirects_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_3.2.2


- name: "SCORED | 3.2.3 | AUDIT | Ensure secure ICMP redirects are not accepted"
  shell: /sbin/sysctl net.ipv4.conf.all.secure_redirects|grep 0 && /sbin/sysctl net.ipv4.conf.default.secure_redirects|grep 0
  register: check_ipv4_redirects_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_3.2.3


- name: "SCORED | 3.2.4 | AUDIT | Ensure suspicious packets are logged"
  shell: /sbin/sysctl net.ipv4.conf.all.log_martians|grep 1 && /sbin/sysctl net.ipv4.conf.default.log_martians|grep 1
  register: check_ipv4_suspicious_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_3.2.4


- name: "SCORED | 3.2.5 | AUDIT | Ensure broadcast ICMP requests are ignored"
  shell: /sbin/sysctl net.ipv4.icmp_echo_ignore_broadcasts|grep 1
  register: check_ipv4_broadcasts_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_3.2.5


- name: "SCORED | 3.2.6 | AUDIT | Ensure bogus ICMP responses are ignored"
  shell: /sbin/sysctl net.ipv4.icmp_ignore_bogus_error_responses|grep 1
  register: check_ipv4_bogos_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_3.2.6


- name: "SCORED | 3.2.7 | AUDIT | Ensure Reverse Path Filtering is enabled"
  shell: /sbin/sysctl net.ipv4.conf.all.rp_filter|grep 1 && /sbin/sysctl net.ipv4.conf.default.rp_filter|grep 1
  register: check_ipv4_pathfilter_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_3.2.7


- name: "SCORED | 3.2.8 | AUDIT | Ensure TCP SYN Cookies is enabled"
  shell: /sbin/sysctl net.ipv4.tcp_syncookies|grep 1
  register: check_ipv4_tcpsyn_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_3.2.8


- name: "SCORED | 3.3.1 | AUDIT | Ensure IPv6 router advertisements are not accepted"
  shell: /sbin/sysctl net.ipv6.conf.all.accept_ra|grep 0 && /sbin/sysctl net.ipv6.conf.default.accept_ra|grep 0
  register: check_ipv6_route_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_3.3.1


- name: "SCORED | 3.3.2 | AUDIT | Ensure IPv6 redirects are not accepted"
  shell: /sbin/sysctl net.ipv6.conf.all.accept_redirects|grep 0 && /sbin/sysctl net.ipv6.conf.default.accept_redirects|grep 0
  register: check_ipv6_redirects_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.3.2


- name: "NOTSCORED | 3.3.3 | AUDIT | Ensure IPv6 is disabled"
  shell: modprobe -c | grep 'options ipv6 disable=1'
  register: check_ipv6_disable_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_3.3.3


- name: "SCORED | 3.4.1 | AUDIT | Ensure TCP Wrappers is installed"
  command: rpm -q tcp_wrappers
  register: check_tcp_wrapper_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_3.4.1


- name: "SCORED | 3.4.2 | AUDIT | Ensure /etc/hosts.allow is configured"
  shell: "/usr/bin/egrep '^ALL' /etc/hosts.allow"
  register: check_host_allow_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_3.4.2


- name: "SCORED | 3.4.3 | AUDIT | Ensure /etc/hosts.deny is configured"
  shell: "/usr/bin/egrep '^ALL: ALL' /etc/hosts.deny"
  register: check_host_deny_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_3.4.3


- name: "SCORED | 3.4.4 | AUDIT | Ensure permissions on /etc/hosts.allow are configured"
  shell: stat -L -c "%a %u %g" /etc/hosts.allow | egrep "644 0 0"
  register: fileperm_host_allow_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_3.4.4


- name: "SCORED | 3.4.5 | AUDIT | Ensure permissions on /etc/hosts.deny are 644"
  shell: stat -L -c "%a %u %g" /etc/hosts.deny | egrep "644 0 0"
  register: fileperm_host_deny_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_3.4.5


- name: "NOTSCORED | 3.5.1 | AUDIT | Ensure DCCP is disabled"
  shell: modprobe -n -v dccp | grep 'install /bin/true'
  register: check_dccp_disable_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_3.5.1


- name: "NOTSCORED | 3.5.2 | AUDIT | Ensure SCTP is disabled"
  shell: modprobe -n -v sctp | grep 'install /bin/true'
  register: check_sctp_disable_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_3.5.2


- name: "NOTSCORED | 3.5.3 | AUDIT | Ensure RDS is disabled"
  shell: modprobe -n -v rds | grep 'install /bin/true'
  register: check_rds_disable_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_3.5.3


- name: "NOTSCORED | 3.5.4 | AUDIT | Ensure TIPC is disabled"
  shell: modprobe -n -v tipc | grep 'install /bin/true'
  register: check_tipc_disable_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_3.5.4


- name: "SCORED | 3.6 | AUDIT | Ensure firewalld is installed and started |Â CUSTOM"
  shell: "systemctl is-enabled firewalld|grep disabled"
  register: check_firewalld_enable_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  when: rhel7cis_firewall == "firewalld"
  tags:
      - level1
      - level2
      - audit
      - rule_3.6



- name: "SCORED | 3.6.1 | AUDIT | Ensure iptables is installed"
  command: rpm -q iptables
  register: iptables_installed_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  when: rhel7cis_firewall == "iptables"
  tags:
      - level1
      - level2
      - audit
      - rule_3.6.1


- name: "SCORED | 3.6.2 | AUDIT | Ensure default deny firewall policy"
  shell: iptables -L | grep 'Chain INPUT' | grep DROP
  register: default_deny_input_policy_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  when: rhel7cis_firewall == "iptables"
  tags:
      - level1
      - level2
      - audit
      - rule_3.6.2

- name: "SCORED | 3.6.2 | AUDIT | Ensure default deny firewall policy"
  shell: iptables -L | grep 'Chain FORWARD' | grep DROP
  register: default_deny_forward_policy_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  when: rhel7cis_firewall == "iptables"
  tags:
      - level1
      - level2
      - audit
      - rule_3.6.2

- name: "SCORED | 3.6.2 | AUDIT | Ensure default deny firewall policy"
  shell: iptables -L | grep 'Chain OUTPUT' | grep DROP
  register: default_deny_output_policy_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  when: rhel7cis_firewall == "iptables"
  tags:
      - level1
      - level2
      - audit
      - rule_3.6.2


- name: "SCORED | 3.6.3 | AUDIT | Ensure loopback traffic is configured"
  shell: iptables -L INPUT -v -n| grep lo | grep ACCEPT
  register: ensure_loopback_interface_accepts_traffic_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  when: rhel7cis_firewall == "iptables"
  tags:
      - level1
      - level2
      - audit
      - rule_3.6.3

- name: "SCORED | 3.6.3 | AUDIT | Ensure loopback traffic is configured"
  shell: iptables -L INPUT -v -n | grep 127.0.0.0/8|grep DROP
  register: ensure_other_interfaces_drop_loopback_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  when: rhel7cis_firewall == "iptables"
  tags:
      - level1
      - level2
      - audit
      - rule_3.6.3


- name: "NOTSCORED | 3.6.4 | AUDIT | Ensure outbound and established connections are configured"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  when: rhel7cis_firewall == "iptables"
  tags:
      - level1
      - level2
      - audit
      - rule_3.6.4


- name: "SCORED | 3.6.5 | AUDIT | Ensure firewall rules exist for all open ports"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  when: rhel7cis_firewall == "iptables"
  tags:
      - level1
      - level2
      - audit
      - rule_3.6.5


- name: "NOTSCORED | 3.7 | AUDIT | Ensure wireless interfaces are disabled"
  command: iwconfig
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.7

