- name: "SCORED | 2.1.1 | AUDIT | Ensure chargen services are not enabled | chargen-dgram"
  shell: "chkconfig --list | grep chargen-dgram |grep -q on"
  register: chargen1_server_enabled_audit
  failed_when: chargen1_server_enabled_audit.rc == 0
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.1.1

- name: "SCORED | 2.1.1 | AUDIT | Ensure chargen services are not enabled | chargen-stream"
  shell: "chkconfig --list | grep chargen-stream |grep -q on"
  register: chargen2_server_enabled_audit
  failed_when: chargen2_server_enabled_audit.rc == 0
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.1.1



- name: "SCORED | 2.1.2 | AUDIT | Ensure daytime services are not enabled | daytime-dgram"
  shell: "chkconfig --list | grep daytime-dgram |grep -q on"
  register: daytime1_server_enabled_audit
  failed_when: daytime1_server_enabled_audit.rc == 0
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.1.2

- name: "SCORED | 2.1.2 | AUDIT | Ensure daytime services are not enabled | daytime-stream"
  shell: "chkconfig --list | grep daytime-stream |grep -q on"
  register: daytime2_server_enabled_audit
  failed_when: daytime2_server_enabled_audit.rc == 0
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.1.2



- name: "SCORED | 2.1.3 | AUDIT | Ensure discard services are not enabled | discard-dgram"
  shell: "chkconfig --list | grep discard-dgram |grep -q on"
  register: discard1_server_enabled_audit
  failed_when: discard1_server_enabled_audit.rc == 0
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.1.3

- name: "SCORED | 2.1.3 | AUDIT | Ensure discard services are not enabled | discard-stream"
  shell: "chkconfig --list | grep discard-stream |grep -q on"
  register: discard2_server_enabled_audit
  failed_when: discard2_server_enabled_audit.rc == 0
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.1.3



- name: "SCORED | 2.1.4 | AUDIT | Ensure echo services are not enabled | echo-dgram"
  shell: "chkconfig --list | grep echo-dgram |grep -q on"
  register: echo1_server_enabled_audit
  failed_when: echo1_server_enabled_audit.rc == 0
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.1.4

- name: "SCORED | 2.1.4 | AUDIT | Ensure echo services are not enabled | echo-stream"
  shell: "chkconfig --list | grep echo-stream |grep -q on"
  register: echo2_server_enabled_audit
  failed_when: echo2_server_enabled_audit.rc == 0
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.1.4



- name: "SCORED | 2.1.5 | AUDIT | Ensure time services are not enabled | time-dgram"
  shell: "chkconfig --list | grep time-dgram |grep -q on"
  register: time1_server_enabled_audit
  failed_when: time1_server_enabled_audit.rc == 0
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.1.5

- name: "SCORED | 2.1.5 | AUDIT | Ensure time services are not enabled | time-stream"
  shell: "chkconfig --list | grep time-stream |grep -q on"
  register: time2_server_enabled_audit
  failed_when: time2_server_enabled_audit.rc == 0
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.1.5



- name: "SCORED | 2.1.6 | AUDIT | Ensure tftp server is not enabled"
  shell: "chkconfig --list | grep tftp |grep -q on"
  register: tftp_server_enabled_audit
  failed_when: tftp_server_enabled_audit.rc == 0
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.1.6


- name: "SCORED | 2.1.7 | AUDIT | Ensure xinetd is not enabled"
  shell: "systemctl is-enabled xinetd"
  register: xinetd_server_enabled_audit
  failed_when: "'enabled' in xinetd_server_enabled_audit.stdout"
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.1.7


- name: "NOTSCORED | 2.2.1.1 | AUDIT | Ensure time synchronization is in use"
  shell: "systemctl is-enabled {{ rhel7cis_time_Synchronization }}"
  register: timesync_server_enabled_audit
  failed_when: "'enabled' in timesync_server_enabled_audit.stdout"
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.2.1.1





- name: "SCORED | 2.2.1.2 | AUDIT | Ensure ntp is configured"
  command: egrep -q "^restrict \-[46] default kod nomodify notrap nopeer noquery" /etc/ntp.conf && grep -q "^server" /etc/ntp.conf && grep -q "^OPTIONS=\"-u ntp:ntp\"" /etc/sysconfig/ntpd
  register: check_ntp_restrict_audit
  failed_when: check_ntp_restrict_audit.rc == 1
  always_run: yes
  changed_when: no
  ignore_errors: yes
  when: rhel7cis_time_Synchronization == "ntp"
  tags:
      - level1
      - audit
      - rule_2.2.1.2




- name: "SCORED | 2.2.1.3 | AUDIT | Ensure chrony is configured"
  command: grep -q "^server" /etc/chrony.conf && egrep -q "OPTIONS=\"\-u chrony\"" /etc/sysconfig/chronyd
  register: check_chrony_server_audit
  failed_when: check_chrony_server_audit.rc == 1
  always_run: yes
  changed_when: no
  ignore_errors: yes
  when: rhel7cis_time_Synchronization == "chrony"
  tags:
      - level1
      - audit
      - rule_2.2.1.3



- name: "SCORED | 2.2.2 | AUDIT | Ensure X Window System is not installed"
  command: rpm -qi xorg-x11*
  register: pkgs_xwindows_installed_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - scored
      - xwindows
      - audit
      - rule_2.2.2


- name: "SCORED | 2.2.3 | AUDIT | Ensure Avahi Server is not enabled"
  command: systemctl is-enabled avahi-daemon
  register: avahi_server_enabled_audit
  failed_when: "'enabled' in avahi_server_enabled_audit.stdout"
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - scored
      - avahi
      - services
      - audit
      - rule_2.2.3


- name: "SCORED | 2.2.4 | AUDIT | Ensure CUPS is not enabled"
  command: systemctl is-enabled cups
  register: cups_server_enabled_audit
  failed_when: "'enabled' in cups_server_enabled_audit.stdout"
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - scored
      - cups
      - services
      - audit
      - rule_2.2.4


- name: "SCORED | 2.2.5 | AUDIT | Ensure DHCP Server is not enabled"
  command: systemctl is-enabled dhcpd
  register: dhcpd_server_enabled_audit
  failed_when: "'enabled' in dhcpd_server_enabled_audit.stdout"
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - scored
      - dhcp
      - services
      - audit
      - rule_2.2.5


- name: "SCORED | 2.2.6 | AUDIT | Ensure LDAP server is not enabled"
  command: systemctl is-enabled slapd
  register: slapd_server_enabled_audit
  failed_when: "'enabled' in slapd_server_enabled_audit.stdout"
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - scored
      - ldap
      - services
      - audit
      - rule_2.2.6


- name: "SCORED | 2.2.7 | AUDIT | Ensure NFS and RPC are not enabled"
  command: systemctl is-enabled nfs rpcbind |grep -q enabled
  register: pkgs_nfs_rpcbind_installed_audit
  failed_when: pkgs_nfs_rpcbind_installed_audit.rc == 0
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - scored
      - nfs
      - rpc
      - services
      - audit
      - rule_2.2.7


- name: "SCORED | 2.2.8 | AUDIT | Ensure DNS Server is not enabled"
  command: systemctl is-enabled named
  register: named_server_enabled_audit
  failed_when: "'enabled' in named_server_enabled_audit.stdout"
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.2.8


- name: "SCORED | 2.2.9 | AUDIT | Ensure FTP Server is not enabled"
  command: systemctl is-enabled vsftpd
  register: vsftpd_server_enabled_audit
  failed_when: "'enabled' in vsftpd_server_enabled_audit.stdout"
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.2.9


- name: "SCORED | 2.2.10 | AUDIT | Ensure HTTP server is not enabled"
  command: systemctl is-enabled httpd
  register: httpd_server_enabled_audit
  failed_when: "'enabled' in httpd_server_enabled_audit.stdout"
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.2.10


- name: "SCORED | 2.2.11 | AUDIT | Ensure IMAP and POP3 server is not enabled"
  command: systemctl is-enabled dovecot
  register: dovecot_server_enabled_audit
  failed_when: "'enabled' in dovecot_server_enabled_audit.stdout"
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.2.11


- name: "SCORED | 2.2.12 | AUDIT | Ensure Samba is not enabled"
  command: systemctl is-enabled smb
  register: smb_server_enabled_audit
  failed_when: "'enabled' in smb_server_enabled_audit.stdout"
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.2.12


- name: "SCORED | 2.2.13 | AUDIT | Ensure HTTP Proxy Server is not enabled"
  command: systemctl is-enabled squid
  register: squid_server_enabled_audit
  failed_when: "'enabled' in squid_server_enabled_audit.stdout"
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.2.13


- name: "SCORED | 2.2.14 | AUDIT | Ensure SNMP Server is not enabled"
  command: systemctl is-enabled snmpd
  register: snmp_server_enabled_audit
  failed_when: "'enabled' in snmp_server_enabled_audit.stdout"
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.2.14


- name: "SCORED | 2.2.15 | AUDIT | Ensure mail transfer agent is configured for local-only mode"
  shell: netstat -an | grep LIST | grep ":25[[:space:]]" |egrep -q '127.0.0.1:25|::1:25'
  register: check_mail_agent_audit
  failed_when: check_mail_agent_audit.rc == 1
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.2.15



- name: "SCORED | 2.2.16 | AUDIT | Ensure NIS Server is not enabled"
  command: systemctl is-enabled ypserv
  register: nis_server_enabled_audit
  failed_when: "'enabled' in nis_server_enabled_audit.stdout"
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.2.16


- name: "SCORED | 2.2.17 | AUDIT | Ensure rsh server is not enabled | rsh.socket"
  command: systemctl is-enabled rsh.socket
  register: rsh_server_enabled_audit
  failed_when: "'enabled' in rsh_server_enabled_audit.stdout"
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.2.17

- name: "SCORED | 2.2.17 | AUDIT | Ensure rsh server is not enabled | rlogin.socket"
  command: systemctl is-enabled rlogin.socket
  register: rlogin_server_enabled_audit
  failed_when: "'enabled' in rlogin_server_enabled_audit.stdout"
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.2.17

- name: "SCORED | 2.2.17 | AUDIT | Ensure rsh server is not enabled | rexec.socket"
  command: systemctl is-enabled rexec.socket
  register: rexec_server_enabled_audit
  failed_when: "'enabled' in rexec_server_enabled_audit.stdout"
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.2.17


- name: "SCORED | 2.2.18 | AUDIT | Ensure telnet server is not enabled"
  command: systemctl is-enabled telnet.socket
  register: telnet_server_enabled_audit
  failed_when: "'enabled' in telnet_server_enabled_audit.stdout"
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.2.18


- name: "SCORED | 2.2.19 | AUDIT | Ensure tftp server is not enabled"
  command: "systemctl is-enabled telnet.socket"
  register: tftp_server_enabled_audit
  failed_when: "'enabled' in tftp_server_enabled_audit.stdout"
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - scored
      - insecure_services
      - tftp
      - audit
      - rule_2.2.19


- name: "SCORED | 2.2.20 | AUDIT | Ensure rsync service is not enabled "
  shell: "systemctl is-enabled rsyncd"
  register: rsyncd_server_enabled_audit
  failed_when: "'enabled' in rsyncd_server_enabled_audit.stdout"
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.2.20


- name: "SCORED | 2.2.21 | AUDIT | Ensure talk server is not enabled"
  shell: "systemctl is-enabled ntalk"
  register: ntalk_server_enabled_audit
  failed_when: "'enabled' in ntalk_server_enabled_audit.stdout"
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.2.21


- name: "SCORED | 2.3.1 | AUDIT | Ensure NIS Client is not installed"
  shell: "rpm -aq | grep -q ypbind"
  register: pkgs_ypbind_installed_audit
  failed_when: pkgs_ypbind_installed_audit.rc == 0
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.3.1


- name: "SCORED | 2.3.2 | AUDIT | Ensure rsh client is not installed"
  shell: "rpm -aq | grep -q rsh"
  register: pkgs_rsh_installed_audit
  failed_when: pkgs_rsh_installed_audit.rc == 0
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.3.2


- name: "SCORED | 2.3.3 | AUDIT | Ensure talk client is not installed"
  shell: "rpm -aq | grep -q talk"
  register: pkgs_talk_installed_audit
  failed_when: pkgs_talk_installed_audit.rc == 0
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.3.3


- name: "SCORED | 2.3.4 | AUDIT | Ensure telnet client is not installed"
  shell: "rpm -aq | grep -q telnet"
  register: pkgs_telnet_installed_audit
  failed_when: pkgs_telnet_installed_audit.rc == 0
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.3.4


- name: "SCORED | 2.3.5 | AUDIT | Ensure LDAP client is not installed"
  shell: "rpm -aq | grep -q openldap-clients"
  register: pkgs_openldap_clients_installed_audit
  failed_when: pkgs_openldap_clients_installed_audit.rc == 0
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - audit
      - rule_2.3.5

