- name: "SCORED | 9.1.2 | AUDIT | Verify Permissions on /etc/passwd"
  shell: stat -L -c "%a %u %g" /etc/hosts.allow | egrep "644 0 0"
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.1.2

- name: "SCORED | 9.1.2 | PATCH | Verify Permissions on /etc/passwd"
  file:
      dest=/etc/passwd
      mode=0644
  tags:
      - level1
      - level2
      - patch
      - rule_9.1.2

- name: "SCORED | 9.1.3 | AUDIT | Verify Permissions on /etc/shadow"
  shell: stat -L -c "%a %u %g" /etc/hosts.allow | egrep "640 0 0"
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.1.3

- name: "SCORED | 9.1.3 | PATCH | Verify Permissions on /etc/shadow"
  file:
      dest=/etc/shadow
      mode=000
  tags:
      - level1
      - level2
      - patch
      - rule_9.1.3

- name: "SCORED | 9.1.4 | AUDIT | Verify Permissions on /etc/gshadow"
  shell: stat -L -c "%a %u %g" /etc/hosts.allow | egrep "0 0 0"
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.1.4

- name: "SCORED | 9.1.4 | PATCH | Verify Permissions on /etc/gshadow"
  file:
      dest=/etc/gshadow
      mode=000
  tags:
      - level1
      - level2
      - patch
      - rule_9.1.4

- name: "SCORED | 9.1.5 | AUDIT | Verify Permissions on /etc/group"
  shell: stat -L -c "%a %u %g" /etc/hosts.allow | egrep "644 0 0"
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.1.5

- name: "SCORED | 9.1.5 | PATCH | Verify Permissions on /etc/group"
  file:
      dest=/etc/group
      mode=0644
  tags:
      - level1
      - level2
      - patch
      - rule_9.1.5

- name: "SCORED | 9.1.6 | AUDIT | Verify User/Group Ownership on /etc/passwd"
  shell: stat -L -c "%u %g" /etc/passwd | egrep "0 0"
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.1.6

- name: "SCORED | 9.1.6 | PATCH | Verify User/Group Ownership on /etc/passwd"
  file:
      dest=/etc/passwd
      owner=root
      group=root
  tags:
      - level1
      - level2
      - patch
      - rule_9.1.6

- name: "SCORED | 9.1.7 | AUDIT | Verify User/Group Ownership on /etc/shadow"
  shell: stat -L -c "%u %g" /etc/shadow | egrep "0 0"
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.1.7

- name: "SCORED | 9.1.7 | PATCH | Verify User/Group Ownership on /etc/shadow"
  file:
      dest=/etc/shadow
      owner=root
      group=root
  tags:
      - level1
      - level2
      - patch
      - rule_9.1.7

- name: "SCORED | 9.1.8 | AUDIT | Verify User/Group Ownership on /etc/gshadow"
  shell: stat -L -c "%u %g" /etc/gshadow | egrep "0 0"
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.1.8

- name: "SCORED | 9.1.8 | PATCH | Verify User/Group Ownership on /etc/gshadow"
  file:
      dest=/etc/gshadow
      owner=root
      group=root
  tags:
      - level1
      - level2
      - patch
      - rule_9.1.8

- name: "SCORED | 9.1.9 | AUDIT | Verify User/Group Ownership on /etc/group"
  shell: stat -L -c "%u %g" /etc/group | egrep "0 0"
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.1.9

- name: "SCORED | 9.1.9 | PATCH | Verify User/Group Ownership on /etc/group"
  file:
      dest=/etc/group
      owner=root
      group=root
  tags:
      - level1
      - level2
      - patch
      - rule_9.1.9

- name: "SCORED | 9.2.2 | AUDIT | Verify No Legacy '+' Entries Exist in /etc/passwd File"
  command: /bin/grep '^+:' /etc/passwd
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.2.2

- name: "SCORED | 9.2.3 | AUDIT | Verify No Legacy '+' Entries Exist in /etc/shadow File"
  command: /bin/grep '^+:' /etc/shadow
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.2.3

- name: "SCORED | 9.2.4 | AUDIT | Verify No Legacy '+' Entries Exist in /etc/group File"
  command: /bin/grep '^+:' /etc/group
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.2.4
