- name: "SCORED | 3.1 | AUDIT | Set Daemon umask"
  command: grep umask /etc/sysconfig/init
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.1

- name: "SCORED | 3.1 | PATCH | Set Daemon umask"
  lineinfile:
      dest=/etc/sysconfig/init
      regexp='^umask'
      line='umask 027'
      state=present
  tags:
      - level1
      - level2
      - patch
      - rule_3.1

- name: "SCORED | 3.2 | AUDIT | Remove the X Window System"
  command: rpm -q xorg-x11-server-common
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.2

- name: "SCORED | 3.2 | PATCH | Remove the X Window System"
  yum:
      name=xorg-x11-server-common
      state=absent
  tags:
      - level1
      - level2
      - patch
      - rule_3.2

- name: "SCORED | 3.3 | AUDIT | Disable Avahi Server"
  command: service avahi-daemon status
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.3

- name: "SCORED | 3.3 | PATCH | Disable Avahi Server"
  yum:
      name=avahi
      state=absent
  tags:
      - level1
      - level2
      - patch
      - rule_3.3

- name: "NOTSCORED | 3.4 | AUDIT | Disable Print Server - CUPS"
  command: systemctl is-enabled cups
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.4

- name: "NOTSCORED | 3.4 | PATCH | Disable Print Server - CUPS"
  yum:
      name=cups
      state=absent
  tags:
      - level1
      - level2
      - patch
      - rule_3.4

- name: "SCORED | 3.5 | AUDIT | Remove DHCP Server"
  command: rpm -q dhcp
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.5

- name: "SCORED | 3.5 | PATCH | Remove DHCP Server"
  yum:
      name=dhcp
      state=absent
  when:
      rhel7cis_dhcp == false
  tags:
      - level1
      - level2
      - patch
      - rule_3.5

- name: "SCORED | 3.6 | AUDIT | Configure Network Time Protocol (NTP)"
  command: grep "restrict default" /etc/ntp.conf
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.6

- name: "SCORED | 3.6 | PATCH | Configure Network Time Protocol (NTP)"
  lineinfile:
      dest=/etc/ntp.conf
      regexp='^restrict default'
      line='restrict default kod nomodify notrap nopeer noquery'
      state=present
  tags:
      - level1
      - level2
      - patch
      - rule_3.6

- name: "SCORED | 3.6 | AUDIT | Configure Network Time Protocol (NTP)"
  command: grep "restrict -6 default" /etc/ntp.conf
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.6

- name: "SCORED | 3.6 | PATCH | Configure Network Time Protocol (NTP)"
  lineinfile:
      dest=/etc/ntp.conf
      regexp='^restrict -6 default'
      line='restrict -6 default kod nomodify notrap nopeer noquery'
      state=present
  tags:
      - level1
      - level2
      - patch
      - rule_3.6

- name: "SCORED | 3.6 | PATCH | Configure Network Time Protocol (NTP)"
  lineinfile:
      dest=/etc/sysconfig/ntpd
      regexp='^OPTIONS'
      line='OPTIONS="-u ntp:ntp"'
      state=present
  tags:
      - level1
      - level2
      - patch
      - rule_3.6

- name: "NOTSCORED | 3.7 | AUDIT | Remove LDAP"
  command: rpm -q openldap-servers
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.7

- name: "NOTSCORED | 3.7 | PATCH | Remove LDAP"
  yum:
      name=openldap-servers
      state=absent
  when:
      rhel7cis_ldap == false
  tags:
      - level1
      - level2
      - patch
      - rule_3.7

- name: "NOTSCORED | 3.8 | AUDIT | Disable NFS and RPC"
  command: systemctl is-enabled nfs
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.8

- name: "NOTSCORED | 3.8 | AUDIT | Disable NFS and RPC"
  command: systemctl is-enabled rpcbind
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.8

- name: "NOTSCORED | 3.8 | PATCH | Disable NFS and RPC"
  command: systemctl disable nfs
  when:
      rhel7cis_nfs == false
  tags:
      - level1
      - level2
      - patch
      - rule_3.8

- name: "NOTSCORED | 3.8 | PATCH | Disable NFS and RPC"
  command: systemctl disable rpcbind
  when:
      rhel7cis_rpc == false
  tags:
      - level1
      - level2
      - patch
      - rule_3.8

- name: "NOTSCORED | 3.9 | AUDIT | Remove DNS Server"
  command: rpm -q bind
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.9

- name: "NOTSCORED | 3.9 | PATCH | Remove DNS Server"
  yum:
      name=bind
      state=absent
  when:
      rhel7cis_bind == false
  tags:
      - level1
      - level2
      - patch
      - rule_3.9

- name: "NOTSCORED | 3.10 | AUDIT | Remove FTP Server"
  command: rpm -q vsftpd
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.10

- name: "NOTSCORED | 3.10 | PATCH | Remove FTP Server"
  yum:
      name=vsftpd
      state=absent
  when:
      rhel7cis_vsftpd == false
  tags:
      - level1
      - level2
      - patch
      - rule_3.10

- name: "NOTSCORED | 3.11 | AUDIT | Remove HTTP Server"
  command: rpm -q httpd
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.11

- name: "NOTSCORED | 3.11 | PATCH | Remove HTTP Server"
  yum:
      name=httpd
      state=absent
  when:
      rhel7cis_httpd == false
  tags:
      - level1
      - level2
      - patch
      - rule_3.11

- name: "NOTSCORED | 3.12 | AUDIT | Remove Dovecot (IMAP and POP3 services)"
  command: rpm -q dovecot
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.12

- name: "NOTSCORED | 3.12 | PATCH | Remove Dovecot (IMAP and POP3 services)"
  yum:
      name=dovecot
      state=absent
  when:
      rhel7cis_dovecot == false
  tags:
      - level1
      - level2
      - patch
      - rule_3.12

- name: "NOTSCORED | 3.13 | AUDIT | Remove Samba"
  command: rpm -q samba
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.13

- name: "NOTSCORED | 3.13 | PATCH | Remove Samba"
  yum:
      name=samba
      state=absent
  when:
      rhel7cis_samba == false
  tags:
      - level1
      - level2
      - patch
      - rule_3.13

- name: "NOTSCORED | 3.14 | AUDIT | Remove HTTP Proxy Server"
  command: rpm -q squid
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.14

- name: "NOTSCORED | 3.14 | PATCH | Remove HTTP Proxy Server"
  yum:
      name=squid
      state=absent
  when:
      rhel7cis_squid == false
  tags:
      - level1
      - level2
      - patch
      - rule_3.14

- name: "NOTSCORED | 3.15 | AUDIT | Remove SNMP Server"
  command: rpm -q net-snmp
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.15

- name: "NOTSCORED | 3.15 | PATCH | Remove SNMP Server"
  yum:
      name=net-snmp
      state=absent
  when:
      rhel7cis_net_snmp == false
  tags:
      - level1
      - level2
      - patch
      - rule_3.15

- name: "SCORED | 3.16 | AUDIT | Configure Mail Transfer Agent for Local-Only Mode"
  command: netstat -ant | grep LIST | grep ":25[[:space:]]"|grep 127.0.0.1
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.16

- name: "SCORED | 3.16 | PATCH | Configure Mail Transfer Agent for Local-Only Mode"
  lineinfile:
      dest=/etc/postfix/main.cf
      regexp='^inet_interfaces'
      line='inet_interfaces = localhost'
      state=present
  tags:
      - level1
      - level2
      - patch
      - rule_3.16

