- name: "SCORED | 3.1.1 | AUDIT | Ensure IP forwarding is disabled"
  shell: /sbin/sysctl net.ipv4.ip_forward|grep 0
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.1.1

- name: "SCORED | 3.1.1 | PATCH | Ensure IP forwarding is disabled"
  sysctl:
      name: net.ipv4.ip_forward
      value: 0
      state: present
      reload: yes
      ignoreerrors: yes
  tags:
      - level1
      - level2
      - patch
      - rule_3.1.1

- name: "SCORED | 3.1.2 | AUDIT | Ensure packet redirect sending is disabled"
  shell: /sbin/sysctl net.ipv4.conf.all.send_redirects | grep 0
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.1.2

- name: "SCORED | 3.1.2 | PATCH | Ensure packet redirect sending is disabled"
  sysctl:
      name: net.ipv4.conf.all.send_redirects
      value: 0
      state: present
      reload: yes
      ignoreerrors: yes
  tags:
      - level1
      - level2
      - patch
      - rule_3.1.2

- name: "SCORED | 3.2.1 | AUDIT | Ensure source routed packets are not accepted"
  shell: /sbin/sysctl net.ipv4.conf.all.accept_source_route | grep 0
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.2.1

- name: "SCORED | 3.2.1 | PATCH | Ensure source routed packets are not accepted"
  sysctl:
      name: net.ipv4.conf.all.accept_source_route
      value: 0
      state: present
      reload: yes
      ignoreerrors: yes
  tags:
      - level1
      - level2
      - patch
      - rule_3.2.1

- name: "SCORED | 3.2.2 | AUDIT | Ensure ICMP redirects are not accepted"
  shell: /sbin/sysctl net.ipv4.conf.all.accept_redirects | grep 0
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.2.2

- name: "SCORED | 3.2.2 | PATCH | Ensure ICMP redirects are not accepted"
  sysctl:
      name: net.ipv4.conf.all.accept_redirects
      value: 0
      state: present
      reload: yes
      ignoreerrors: yes
  tags:
      - level1
      - level2
      - patch
      - rule_3.2.2

- name: "SCORED | 3.2.3 | AUDIT | Ensure secure ICMP redirects are not accepted"
  shell: /sbin/sysctl net.ipv4.conf.default.accept_redirects | grep 0
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.2.3

- name: "SCORED | 3.2.3 | PATCH | Ensure secure ICMP redirects are not accepted"
  sysctl:
      name: net.ipv4.conf.default.accept_redirects
      value: 0
      state: present
      reload: yes
      ignoreerrors: yes
  tags:
      - level1
      - level2
      - patch
      - rule_3.2.3

- name: "SCORED | 3.2.4 | AUDIT | Ensure suspicious packets are logged"
  shell: /sbin/sysctl net.ipv4.conf.all.log_martians | grep 1
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.2.4

- name: "SCORED | 3.2.4 | PATCH | Ensure suspicious packets are logged"
  sysctl:
      name: net.ipv4.conf.all.log_martians
      value: 1
      state: present
      reload: yes
      ignoreerrors: yes
  tags:
      - level1
      - level2
      - patch
      - rule_3.2.4

- name: "SCORED | 3.2.5 | AUDIT | Ensure broadcast ICMP requests are ignored"
  shell: /sbin/sysctl net.ipv4.icmp_echo_ignore_broadcasts | grep 1
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.2.5

- name: "SCORED | 3.2.5 | PATCH | Ensure broadcast ICMP requests are ignored"
  sysctl:
      name: net.ipv4.icmp_echo_ignore_broadcasts
      value: 1
      state: present
      reload: yes
      ignoreerrors: yes
  tags:
      - level1
      - level2
      - patch
      - rule_3.2.5

- name: "SCORED | 3.2.6 | AUDIT | Ensure bogus ICMP responses are ignored"
  shell: /sbin/sysctl net.ipv4.icmp_ignore_bogus_error_responses | grep 1
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.2.6

- name: "SCORED | 3.2.6 | PATCH | Ensure bogus ICMP responses are ignored"
  sysctl:
      name: net.ipv4.icmp_ignore_bogus_error_responses
      value: 1
      state: present
      reload: yes
      ignoreerrors: yes
  tags:
      - level1
      - level2
      - patch
      - rule_3.2.6

- name: "SCORED | 3.2.7 | AUDIT | Ensure Reverse Path Filtering is enabled"
  shell: /sbin/sysctl net.ipv4.conf.all.rp_filter | grep 1
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.2.7

- name: "SCORED | 3.2.7 | PATCH | Ensure Reverse Path Filtering is enabled"
  sysctl:
      name: net.ipv4.conf.all.rp_filter
      value: 1
      state: present
      reload: yes
      ignoreerrors: yes
  tags:
      - level1
      - level2
      - patch
      - rule_3.2.7

- name: "SCORED | 3.2.8 | AUDIT | Ensure TCP SYN Cookies is enabled"
  shell: /sbin/sysctl net.ipv4.tcp_syncookies | grep 1
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.2.8

- name: "SCORED | 3.2.8 | PATCH | Ensure TCP SYN Cookies is enabled"
  sysctl:
      name: net.ipv4.tcp_syncookies
      value: 1
      state: present
      reload: yes
      ignoreerrors: yes
  tags:
      - level1
      - level2
      - patch
      - rule_3.2.8

- name: "SCORED | 3.3.1 | AUDIT | Ensure IPv6 router advertisements are not accepted"
  shell: /sbin/sysctl net.ipv6.conf.all.accept_ra | grep 0
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.3.1

- name: "SCORED | 3.3.1 | PATCH | Ensure IPv6 router advertisements are not accepted"
  sysctl:
      name: net.ipv6.conf.all.accept_ra
      value: 0
      state: present
      reload: yes
      ignoreerrors: yes
  tags:
      - level1
      - level2
      - patch
      - rule_3.3.1

- name: "SCORED | 3.3.2 | AUDIT | Ensure IPv6 redirects are not accepted"
  shell: /sbin/sysctl net.ipv6.conf.all.accept_redirect | grep 0
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.3.2

- name: "SCORED | 3.3.2 | PATCH | Ensure IPv6 redirects are not accepted"
  sysctl:
      name: net.ipv6.conf.all.accept_redirect
      value: 0
      state: present
      reload: yes
      ignoreerrors: yes
  tags:
      - level1
      - level2
      - patch
      - rule_3.3.2

- name: "NOTSCORED | 3.3.3 | AUDIT | Ensure IPv6 is disabled"
  shell: /sbin/sysctl net.ipv6.conf.all.disable_ipv6 | grep 1
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.3.3

- name: "NOTSCORED | 3.3.3 | PATCH | Ensure IPv6 is disabled"
  sysctl:
      name: net.ipv6.conf.all.disable_ipv6
      value: 1
      state: present
      reload: yes
      ignoreerrors: yes
  tags:
      - level1
      - level2
      - patch
      - rule_3.3.3

- name: "SCORED | 3.4.1 | AUDIT | Ensure TCP Wrappers is installed"
  command: rpm -q tcp_wrappers
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.4.1

- name: "SCORED | 3.4.1 | PATCH | Ensure TCP Wrappers is installed"
  yum:
      name=tcp_wrappers
      state=installed
  tags:
      - level1
      - level2
      - patch
      - rule_3.4.1

- name: "SCORED | 3.4.2 | AUDIT | Ensure /etc/hosts.allow is configured"
  command: grep -v '^#' /etc/hosts.allow
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.4.2

- name: "SCORED | 3.4.2 | PATCH | Ensure /etc/hosts.allow is configured"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.4.2

- name: "SCORED | 3.4.3 | AUDIT | Ensure /etc/hosts.deny is configured"
  command: grep '^ALL: ALL' /etc/hosts.deny
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.4.3

- name: "SCORED | 3.4.3 | PATCH | Ensure /etc/hosts.deny is configured"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.4.3

- name: "SCORED | 3.4.4 | AUDIT | Ensure permissions on /etc/hosts.allow are configured"
  shell: stat -L -c "%a %u %g" /etc/hosts.allow | egrep "644 0 0"
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.4.4

- name: "SCORED | 3.4.4 | PATCH | Ensure permissions on /etc/hosts.allow are configured"
  file:
      dest=/etc/hosts.allow
      owner=root
      group=root
      mode=0644
  tags:
      - level1
      - level2
      - patch
      - rule_3.4.4

- name: "SCORED | 3.4.5 | AUDIT | Ensure permissions on /etc/hosts.deny are 644"
  shell: stat -L -c "%a %u %g" /etc/hosts.allow | egrep "644 0 0"
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.4.5

- name: "SCORED | 3.4.5 | PATCH | Ensure permissions on /etc/hosts.deny are 644"
  file:
      dest=/etc/hosts.deny
      owner=root
      group=root
      mode=0644
  tags:
      - level1
      - level2
      - patch
      - rule_3.4.5

- name: "NOTSCORED | 3.5.1 | AUDIT | Ensure DCCP is disabled"
  command: grep -rs "^install\s*dccp\s*/bin/true$" /etc/modprobe.d
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.5.1

- name: "NOTSCORED | 3.5.1 | PATCH | Ensure DCCP is disabled"
  lineinfile:
      state: present
      create: yes
      line: install dccp /bin/true
      dest: /etc/modprobe.d/disable-dccp.conf
      owner: root
      group: root
      mode: "0644"
  tags:
      - level1
      - level2
      - patch
      - rule_3.5.1

- name: "NOTSCORED | 3.5.2 | AUDIT | Ensure SCTP is disabled"
  command: grep -rs "^install\s*sctp\s*/bin/true$" /etc/modprobe.d
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.5.2

- name: "NOTSCORED | 3.5.2 | PATCH | Ensure SCTP is disabled"
  lineinfile:
      state: present
      create: yes
      line: install sctp /bin/true
      dest: /etc/modprobe.d/disable-sctp.conf
      owner: root
      group: root
      mode: "0644"
  tags:
      - level1
      - level2
      - patch
      - rule_3.5.2

- name: "NOTSCORED | 3.5.3 | AUDIT | Ensure RDS is disabled"
  shell: find /etc/modprobe.* -type f -name '*.conf' -exec grep -ls '^install rds /bin/(true|false)' {} \;
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.5.3

- name: "NOTSCORED | 3.5.3 | PATCH | Ensure RDS is disabled"
  copy:
      backup: no
      src: disable-rds.conf
      dest: /etc/modprobe.d/disable-rds.conf
      owner: root
      group: root
      mode: 0644
  tags:
      - level1
      - level2
      - patch
      - rule_3.5.3

- name: "NOTSCORED | 3.5.4 | AUDIT | Ensure TIPC is disabled"
  command: grep -rs "^install\s*tipc\s*/bin/true$" /etc/modprobe.d
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.5.4

- name: "NOTSCORED | 3.5.4 | PATCH | Ensure TIPC is disabled"
  lineinfile:
      state: present
      create: yes
      line: install tipc /bin/true
      dest: /etc/modprobe.d/disable-tipc.conf
      owner: root
      group: root
      mode: "0644"
  tags:
      - level1
      - level2
      - patch
      - rule_3.5.4

- name: "SCORED | 3.6.1 | AUDIT | Ensure iptables is installed"
  command: rpm -q iptables
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.6.1

- name: "SCORED | 3.6.1 | PATCH | Ensure iptables is installed"
  yum:
      name=iptables
      state=installed
  tags:
      - level1
      - level2
      - patch
      - rule_3.6.1

- name: "SCORED | 3.6.2 | AUDIT | Ensure default deny firewall policy"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.6.2

- name: "SCORED | 3.6.2 | PATCH | Ensure default deny firewall policy"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.6.2

- name: "SCORED | 3.6.3 | AUDIT | Ensure loopback traffic is configured"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.6.3

- name: "SCORED | 3.6.3 | PATCH | Ensure loopback traffic is configured"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.6.3

- name: "NOTSCORED | 3.6.4 | AUDIT | Ensure outbound and established connections are configured"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.6.4

- name: "NOTSCORED | 3.6.4 | PATCH | Ensure outbound and established connections are configured"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.6.4

- name: "SCORED | 3.6.5 | AUDIT | Ensure firewall rules exist for all open ports"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.6.5

- name: "SCORED | 3.6.5 | PATCH | Ensure firewall rules exist for all open ports"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.6.5

- name: "NOTSCORED | 3.7 | AUDIT | Ensure wireless interfaces are disabled"
  command: iwconfig
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.7

- name: "NOTSCORED | 3.7 | PATCH | Ensure wireless interfaces are disabled"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.7

